### ISSUE TITLE
Indention broken 

### ISSUE THREAD

**Issue by mojotx** [chrisbra/vim-sh-indent#11]
This is using the tag 20190202. 

Create a file with the following, and re-indent with `gg=G`:
```sh
#!/bin/sh

if [[ /bin/true ]]; then
        echo "true"
else
        echo "false"
        if [[ /bin/false ]]; then
                echo "false"
        else
                echo "true"
        fi
        fi
        if [[ /bin/true ]]
        then
                echo "true"
        else
                echo "false"
                if [[ /bin/false ]]
                then
                        echo "false"
                else
                        echo "true"
        fi
        fi
```

**Comment by raghuvrao** [comment]
Here is probably the minimal test:

```
if true; then
    if true; then
        true
    fi
fi
```

With `gg=G`, the above is indented as follows:

```
if true; then
    if true; then
        true
    fi
    fi
```

Upon putting the above test case into another `if ... fi` block, the indentation comes out as follows:

```
if true; then
    if true; then
        if true; then
            true
        fi
        fi
        fi
```

The closing `fi` statements always align to the most recent `if`, and not to the actual corresponding `if`.

This problem did not exist in versions of `indent/sh.vim` prior to commit 2c2da6620d96bdc01f75ab8b1ed82cebad6eff01.

**Comment by chrisbra** [comment]
okay, I think I fixed it. Please verify

**Comment by mojotx** [comment]
I'm confirming that this appears to be resolved with the latest fix. Thanks!
