### ISSUE TITLE
Multi-line array variable in bash with filetype sh does not indent correctly

### ISSUE THREAD

**Issue by 3N4N** [chrisbra/vim-sh-indent#13]
I have the following bash array after automatic indentation, both on pressing carriage return when was editing in `:h Insert mode` and doing `=ip` on the block in `:h Normal-mode`

```
DOTFILES=(
".bashrc"
".bash_profile"
".gitconfig"
".profile"
)
```
Trying with `nvim -u NORC` yielded the same result, so I'm guessing it's the default `/usr/share/nvim/runtime/indent/sh.vim` indent file in action. Output of `:set ft?` is `filetype=sh`.

I would like to have the aforementioned array with the following indentation:
```
DOTFILES=(
	".bashrc"
	".bash_profile"
	".gitconfig"
	".profile"
)
```

How do I do that?

**Comment by chrisbra** [comment]
should work now.

**Comment by 3N4N** [comment]
@chrisbra, Thanks.
