### ISSUE TITLE
autoindent during typing un-indents "fi" too far

### ISSUE THREAD

**Issue by aswild** [chrisbra/vim-sh-indent#15]
Regression from https://github.com/chrisbra/vim-sh-indent/commit/ef2e050b690bab58ed3d3dfd51147f9bcd2cf870 which changed to using the `searchpair` function.

This seems to happen whenever I type `fi` to end an if statement that's indented.

```bash
1 if a; then
2     b
3     if c; then
4         d
5     fi
6 fi
```

When I type the `fi` on line 5, it's un-indented back to column 1 (matching the `if` on line 1) rather than to column 5 (matching the if on line 3).

When typing the `fi` on line 5, the cursor is in the column with the `i` character and the backwards `searchpair` finds the `if` on line 1 rather than line 3. This is because since the cursor is after the `fi`, it's found and assumed to be a nested if/fi pair.

The `searchpair` documentation suggests **When searching backwards and {end} is more than one character, it may be useful to put "\zs" at the end of the pattern...**
In my tests, it looks like this works, though I'm not totally clear what the `\zs` does. Somehow it's moving where the start of the pattern is so that the searchpair is able to consider the fi right before cursor not included in the first match.

Here's a patch which I believe fixes the issue.
```diff
diff --git a/indent/sh.vim b/indent/sh.vim
index 520d3ee..de88663 100644
--- a/indent/sh.vim
+++ b/indent/sh.vim
@@ -127,7 +127,7 @@ function! GetShIndent()
   " Current line is a endif line, so get indent from start of "if condition" line
   " TODO: should we do the same for other "end" lines?
   if curline =~ '^\s*\%(fi\);\?\s*\%(#.*\)\=$'
-    let previous_line = searchpair('\<if\>', '', '\<fi\>', 'bnW')
+    let previous_line = searchpair('\<if\>', '', '\<fi\>\zs', 'bnW')
     if previous_line > 0
       let ind = indent(previous_line)
     endif
```

**Comment by chrisbra** [comment]
ah, sounds reasonable. Can you please create a PR? I'll try to come up with a test case then. Thanks!

**Comment by aswild** [comment]
PR is up. I'm not sure how to write a test case for insert-mode stuff
