### ISSUE TITLE
wrong indentation when a comment contains the `if` keyword inside an `if` block

### ISSUE THREAD

**Issue by lacygoill** [chrisbra/vim-sh-indent#17]
Consider this bash script written in `/tmp/sh.sh`:

    #!/bin/bash

    func() {
      if 1; then
        # a comment containing the if keyword
        echo
      else
        echo
      fi
    }

If I start Vim like this:

    $ vim -Nu NONE --cmd 'filetype indent on' /tmp/sh.sh

And press `=G` while the cursor is on the first line, the buffer becomes:

    #!/bin/bash

    func() {
            if 1; then
                    # a comment containing the if keyword
                    echo
            else
                    echo
                    fi
            }

If I remove the `if` keyword in the comment:

    #!/bin/bash

    func() {
      if 1; then
        # a comment containing the keyword
        echo
      else
        echo
      fi
    }

Pressing `=G` while the cursor is on the first line indents the buffer like this:

    #!/bin/bash

    func() {
            if 1; then
                    # a comment containing the keyword
                    echo
            else
                    echo
            fi
    }

I would expect the indentation to be identical in both cases.
The last one seems better.
The first one gives 2 levels of indentation for the `fi` line (instead of 1), and 1 level of indentation for the closing bracket (instead of 0).

**Comment by lacygoill** [comment]
The same issue seems to apply to a string containing the `if` keyword, when it's inside an `if` block.
For example, this buffer:

    #!/bin/bash

    func() {
      if 1; then
        echo 'a string containing the if keyword'
      else
        echo
      fi
    }

is indented by `gg=G` like this:

    #!/bin/bash

    func() {
      if 1; then
        echo 'a string containing the if keyword'
      else
        echo
        fi
      }

**Comment by lacygoill** [comment]
For the moment, I deal with this issue by replacing the `i` in an `if` word (inside a comment inside an `if` block), with `і` (unicode codepoint 456).
And `I` (49) in `If` with `І` (406).

**Comment by mojotx** [comment]
I can confirm this happens for me with vim 8.1.1742. 

It does *NOT* happen with Vim 7.4.160, which is the "stock" Vim on RHEL 7.5, nor does it happen with the stock Vim 8.0 on macOS 10.14.6 "Mojave."

If I find time later, I will use `git bisect` to figure out when it broke.

**Comment by lacygoill** [comment]
I bisected the issue to this commit: https://github.com/chrisbra/vim-sh-indent/commit/ef2e050b690bab58ed3d3dfd51147f9bcd2cf870

**Comment by chrisbra** [comment]
Can you check this patch please:

```patch
diff --git a/indent/sh.vim b/indent/sh.vim
index 601f210..b8fe2ef 100644
--- a/indent/sh.vim
+++ b/indent/sh.vim
@@ -131,7 +131,8 @@ function! GetShIndent()
   " Current line is a endif line, so get indent from start of "if condition" line
   " TODO: should we do the same for other "end" lines?
   if curline =~ '^\s*\%(fi\);\?\s*\%(#.*\)\=$'
-    let previous_line = searchpair('\<if\>', '', '\<fi\>\zs', 'bnW')
+    let ind = indent(v:lnum)
+    let previous_line = searchpair('\<if\>', '', '\<fi\>\zs', 'bnW', 'synIDattr(synID(line("."),col("."), 1),"name") =~? "comment")
     if previous_line > 0
       let ind = indent(previous_line)
     endif
```

**Comment by lacygoill** [comment]
I've just tested the patch and it seems to fix the issue.
I can't reproduce it anymore using the previous 2 examples.
Thank you very much for the patch.

**Comment by mojotx** [comment]
This seems to help, but following the instructions of using `vim -Nu NONE --cmd 'filetype indent on'` followed by `=G` on the first line, the last `fi` is not reindented. 

In other words, it goes from this:
```
#!/bin/bash

func() {
  if 1; then
    # a comment containing the if keyword
    echo
  else
    echo
  fi
}
```

To this:
```
#!/bin/bash

func() {
        if 1; then
                # a comment containing the if keyword
                echo
        else
                echo
  fi
}
```

So it's better, but ideally I would think it would reindent the `fi` to match the `if`. 
This is with vim 8.1.1746, which is the latest as of the current moment.

**Comment by chrisbra** [comment]
Yeah, it also broke a test, which is why I didn't push it yet. I'll have to see if there is a nice way to fix it.

**Comment by chrisbra** [comment]
okay, should be fixed now.
