### ISSUE TITLE
Problem with here documents

### ISSUE THREAD

**Issue by ghost** [chrisbra/vim-sh-indent#3]
Hi @chrisbra, I think you saw the issue Chiel92/vim-autoformat#142 . I'll try to be clear about the problem.

When we call your script to "format" the source when it's a shell script, the block inside [here doc](http://www.tldp.org/LDP/abs/html/here-docs.html) gets indented, but its not good because if we indent the block the parser wont find the the delimiter of the block.

**Comment by chrisbra** [comment]
please try current head
