### ISSUE TITLE
preserve indentation within heredocs?

### ISSUE THREAD

**Issue by kevinushey** [chrisbra/vim-sh-indent#4]
Right now, indentation within heredocs appears to be collapsed to 0, e.g. something like this will lose its indentation:

```
read -r -d '' VARIABLE <<- EOF
(this is
 (some text
  (with funky
   (indentation))))
EOF
```

Within the heredoc, `GetShIndent()` returns 0 for each line; however, I think it would be better to just preserve pre-existing indentation within these cases.

We could possibly piggy back on the syntax highlight rules, e.g. something like this could work

```
" Preserve indentation for heredoc
let Syntax = synIDattr(synID(line("."), col("."), 1), "name")
if Syntax =~ "HereDoc"
    return indent(line("."))
endif
```

Thoughts?

**Comment by chrisbra** [comment]
i pushed a fix. Let's see how well this works.

**Comment by kevinushey** [comment]
Thank you very much!
