### ISSUE TITLE
Bad "if" indent when a command option contains the word "if"

### ISSUE THREAD

**Issue by FoxCie** [chrisbra/vim-sh-indent#40]
It seems that having options containing the word `if` breaks the indentation :
```sh
if true; then
    if false; then
        cmd with --if-option
    fi
fi
```

indents as : 
```sh
if true; then
    if false; then
        cmd with --if-option
        fi
    fi
```

It is related to the previous issue #20 , and from what I tested, tweaking the regex in the call to `searchpair` to something like `'[^-]\<if\>'` instead of `'\<if\>'` fixes the issue. I do not know if it breaks things elsewhere though.

To be more precise, I am not sure if the difference between the character set of `'\<'` and the token separators used by the shell parser is restricted to `-`, otherwise, the issue would arise for all characters in that set.

EDIT: as we could have expected, it also fails with options containing --fi : 
```sh
if true; then
    if false; then
        cmd with --fi-option
fi
fi
```
Using the same trick on the end part of `searchpair()` (`'\<fi\>\zs'` --> `'[^-]\<fi\>\zs'`) fixes this behaviour.

EDIT 2: I also noticed that the same behaviour appears when a comment ends with `fi` : 
```sh
if true; then
    if false; then
        # fi
fi
fi
```

This seems to be caused by the use of the `'\zs'` character at the end of the end string, which puts the cursor at the end instead of the beginning. I think it causes the cursor to be positioned after the last character of the line, thus the syntax name is not retrieved correctly, and the comment is not detected.

**Comment by chrisbra** [comment]
I can only reproduce issue 2 and 3. Those should be fixed now. Please verify

**Comment by FoxCie** [comment]
Hi, indeed, everything seems to be fixed now (even the first one, that should be fixed by the use of the `option` syntax element if I understand that correctly).

Thank you for the (very) quick fix !
