### ISSUE TITLE
sh-indent affecting indentation in C code.

### ISSUE THREAD

**Issue by ppsysdev** [chrisbra/vim-sh-indent#5]
**## Can you please guide how we could restrict the effect to shell [sh,ksh,bash,zsh,tcsh] scripts only ?**

When I put sh.vim in ~/.vimrc/plugin/, indentation for sh files works perfect.
However indentation in C files goes on toss.

Steps: 
1. Open file in vim
2. `gg Shit+V Shitf+G =`

Expected file:
```
#include <unistd.h>
int main()
{
    pid_t pid, sid;

    /* Fork off the parent process */
    pid = fork();
    if (pid <= -1)
    {
        /* exit(EXIT_FAILURE); */
    }
}
// vi: ft=c
```

What I get:
```
#include <unistd.h>
int main()
{
    pid_t pid, sid;

    /* Fork off the parent process */
    pid = fork();
    if (pid <= -1)
        {
            /* exit(EXIT_FAILURE); */
        }
    }
    // vi: ft=c
```

**Comment by chrisbra** [comment]
that is an indent script. You need to put that below `~/.vim/indent/sh.vim`. Make sure you enable filetype plugins and indent `:filetype plugin indent on`

**Comment by ppsysdev** [comment]
Thanks Chris, I do have indent and plugin as on in .vimrc file

If I renamed sh.vim as sh.vim__ (so that this file would not load).

Then indentation worked perfectly fine in C code.

**Comment by chrisbra** [comment]
that is most likely the wrong approach. Remember, this is an indent plugin. So Vim expects it below "indent" directory with the name of the filetype for which the indenting should apply (so e.g. save it as `~/.vim/indent/sh.vim` so it will be used for the `sh` filetype)

**Comment by ppsysdev** [comment]
Nope, ~/.vim/indent/sh.vim not working for me for sh file. May be because of my vimrc. I would check again later, and if couldn't get it to work then provide you more details.
