### ISSUE TITLE
indentation within braced expressions?

### ISSUE THREAD

**Issue by kevinushey** [chrisbra/vim-sh-indent#6]
With bash, it can be useful to handle expressions that return a non-zero exit code with something like (silly but illustrative example):

```
cd build || {
    echo "Failed to move to build directory"
    exit 1
}
```

However, this is currently indented as (using two examples)

```
cd build || {
    echo "Failed to move to build directory"
exit 1
}
```

Can the indentation be made uniform for this case?

**Comment by chrisbra** [comment]
Hm, that is tricky. the whole continuation thing looks kind of strange. I'll have to think about that one a bit to fix it properly without introducing regressions...

**Comment by kevinushey** [comment]
Awesome! Thank you for the fix :-)
